export const GET_GROUP_PENDING = 'GET_GROUP_PENDING';
export const GET_GROUP_SUCCESS = 'GET_GROUP_SUCCESS';
export const GET_GROUP_ERROR = 'GET_GROUP_ERROR';

export const GET_USERS_IN_GROUP_PENDING = 'GET_USERS_IN_GROUP_PENDING';
export const GET_USERS_IN_GROUP_SUCCESS = 'GET_USERS_IN_GROUP_SUCCESS';
export const GET_USERS_IN_GROUP_ERROR = 'GET_USERS_IN_GROUP_ERROR';

export const GET_USERS_NOT_IN_GROUP_PENDING = 'GET_USERS_NOT_IN_GROUP_PENDING';
export const GET_USERS_NOT_IN_GROUP_SUCCESS = 'GET_USERS_NOT_IN_GROUP_SUCCESS';
export const GET_USERS_NOT_IN_GROUP_ERROR = 'GET_USERS_NOT_IN_GROUP_ERROR';

export const ADD_USER_TO_GROUP_PENDING = 'ADD_USER_TO_GROUP_PENDING';
export const ADD_USER_TO_GROUP_SUCCESS = 'ADD_USER_TO_GROUP_SUCCESS';
export const ADD_USER_TO_GROUP_ERROR = 'ADD_USER_TO_GROUP_ERROR';

export const REMOVE_USER_FROM_GROUP_PENDING = 'REMOVE_USER_FROM_GROUP_PENDING';
export const REMOVE_USER_FROM_GROUP_SUCCESS = 'REMOVE_USER_FROM_GROUP_SUCCESS';
export const REMOVE_USER_FROM_GROUP_ERROR = 'REMOVE_USER_FROM_GROUP_ERROR';

export const ADD_GROUP_PENDING = 'ADD_GROUP_PENDING';
export const ADD_GROUP_SUCCESS = 'ADD_GROUP_SUCCESS';
export const ADD_GROUP_ERROR = 'ADD_GROUP_ERROR';