export const GET_GROUP_LIST_PENDING = 'GET_GROUP_LIST_PENDING';
export const GET_GROUP_LIST_SUCCESS = 'GET_GROUP_LIST_SUCCESS';
export const GET_GROUP_LIST_ERROR = 'GET_GROUP_LIST_ERROR';
export const ADD_GROUP_PENDING = 'ADD_GROUP_PENDING';
export const ADD_GROUP_SUCCESS = 'ADD_GROUP_SUCCESS';
export const ADD_GROUP_ERROR = 'ADD_GROUP_ERROR';