version: "3.0"

services:
  server:
    image: node:14.15.0
    volumes:
      - ./api:/app
    working_dir: /app
    command: sh -c "npm install && npm run start"
    ports: 
      - 3456:3456
  
  client:
    image: node:14.15.0
    volumes:
      - ./client:/app
    working_dir: /app
    command: sh -c "npm install && npm run start"
    ports:
      - 3000:3000