const GET_USER_LIST_PENDING = 'GET_USER_LIST_PENDING';
const GET_USER_LIST_SUCCESS = 'GET_USER_LIST_SUCCESS';
const GET_USER_LIST_ERROR = 'GET_USER_LIST_ERROR';

export {
  GET_USER_LIST_PENDING,
  GET_USER_LIST_SUCCESS,
  GET_USER_LIST_ERROR
}