export const GET_USERS_PENDING = 'GET_USERS_PENDING';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_ERROR   = 'GET_USERS_ERROR';
export const ADD_USER_PENDING  = 'ADD_USER_PENDING';
export const ADD_USER_SUCCESS  = 'ADD_USER_SUCCESS';
export const ADD_USER_ERROR    = 'ADD_USER_ERROR';