export const GET_TEST_PENDING = 'GET_TEST_PENDING';
export const GET_TEST_SUCCESS = 'GET_TEST_SUCCESS';
export const GET_TEST_ERROR = 'GET_TEST_ERROR';

export const GET_ASSIGNED_GROUPS_PENDING = 'GET_ASSIGNED_GROUPS_PENDING';
export const GET_ASSIGNED_GROUPS_SUCCESS = 'GET_ASSIGNED_GROUPS_SUCCESS';
export const GET_ASSIGNED_GROUPS_ERROR = 'GET_ASSIGNED_GROUPS_ERROR';