export const CLEAR_ASSESSMENT = 'CLEAR_ASSESSMENT';
export const CLEAR_CHANGED_QUESTIONS = 'CLEAR_CHANGED_QUESTIONS';
export const SAVE_ANSWERS_PENDING = 'SAVE_ANSWERS_PENDING';
export const SAVE_ANSWERS_SUCCESS = 'SAVE_ANSWERS_SUCCESS';
export const SAVE_ANSWERS_ERROR   = 'SAVE_ANSWERS_ERROR';
export const SET_QUESTION = 'SET_QUESTION';
export const TOGGLE_ANSWER = 'TOGGLE_ANSWER';
export const FLAG_QUESTION = 'FLAG_QUESTION';