export const ADD_EVENT_PENDING  = 'ADD_EVENT_PENDING';
export const ADD_EVENT_SUCCESS  = 'ADD_EVENT_SUCCESS';
export const ADD_EVENT_ERROR    = 'ADD_EVENT_ERROR';

export const SAVE_EVENT_PENDING  = 'SAVE_EVENT_PENDING';
export const SAVE_EVENT_SUCCESS  = 'SAVE_EVENT_SUCCESS';
export const SAVE_EVENT_ERROR    = 'SAVE_EVENT_ERROR';

export const DELETE_EVENT_PENDING = 'DELETE_EVENT_PENDING';
export const DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS';
export const DELETE_EVENT_ERROR   = 'DELETE_EVENT_ERROR';