export const ADD_EVENT_PENDING  = 'ADD_EVENT_PENDING';
export const ADD_EVENT_SUCCESS  = 'ADD_EVENT_SUCCESS';
export const ADD_EVENT_ERROR    = 'ADD_EVENT_ERROR';

export const SAVE_EVENT_PENDING  = 'SAVE_EVENT_PENDING';
export const SAVE_EVENT_SUCCESS  = 'SAVE_EVENT_SUCCESS';
export const SAVE_EVENT_ERROR    = 'SAVE_EVENT_ERROR';

export const DELETE_EVENT_PENDING = 'DELETE_EVENT_PENDING';
export const DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS';
export const DELETE_EVENT_ERROR   = 'DELETE_EVENT_ERROR';

export const GET_EVENT_PENDING = 'GET_EVENT_PENDING';
export const GET_EVENT_SUCCESS = 'GET_EVENT_SUCCESS';
export const GET_EVENT_ERROR = 'GET_EVENT_ERROR';

export const GET_ASSIGNED_GROUPS_PENDING = 'GET_ASSIGNED_GROUPS_PENDING';
export const GET_ASSIGNED_GROUPS_SUCCESS = 'GET_ASSIGNED_GROUPS_SUCCESS';
export const GET_ASSIGNED_GROUPS_ERROR = 'GET_ASSIGNED_GROUPS_ERROR';

export const ADD_GROUP_PENDING = 'ADD_GROUP_PENDING';
export const ADD_GROUP_SUCCESS = 'ADD_GROUP_SUCCESS';
export const ADD_GROUP_ERROR = 'ADD_GROUP_ERROR';

export const REMOVE_GROUP_PENDING = 'REMOVE_GROUP_PENDING';
export const REMOVE_GROUP_SUCCESS = 'REMOVE_GROUP_SUCCESS';
export const REMOVE_GROUP_ERROR = 'REMOVE_GROUP_ERROR';