export const ADD_GROUP_PENDING = 'ADD_GROUP_PENDING';
export const ADD_GROUP_SUCCESS = 'ADD_GROUP_SUCCESS';
export const ADD_GROUP_ERROR = 'ADD_GROUP_ERROR';

export const SAVE_GROUP_PENDING = 'SAVE_GROUP_PENDING';
export const SAVE_GROUP_SUCCESS = 'SAVE_GROUP_SUCCESS';
export const SAVE_GROUP_ERROR = 'SAVE_GROUP_ERROR';

export const GET_GROUP_LIST_PENDING = 'GET_GROUP_LIST_PENDING';
export const GET_GROUP_LIST_SUCCESS = 'GET_GROUP_LIST_SUCCESS';
export const GET_GROUP_LIST_ERROR = 'GET_GROUP_LIST_ERROR';

export const GET_GROUP_PENDING = 'GET_GROUP_PENDING';
export const GET_GROUP_SUCCESS = 'GET_GROUP_SUCCESS';
export const GET_GROUP_ERROR = 'GET_GROUP_ERROR';

export const GET_ASSIGNED_USERS_PENDING = 'GET_ASSIGNED_USERS_PENDING';
export const GET_ASSIGNED_USERS_SUCCESS = 'GET_ASSIGNED_USERS_SUCCESS';
export const GET_ASSIGNED_USERS_ERROR = 'GET_ASSIGNED_USERS_ERROR';

export const ADD_USER_TO_GROUP_PENDING = 'ADD_USER_TO_GROUP_PENDING';
export const ADD_USER_TO_GROUP_SUCCESS = 'ADD_USER_TO_GROUP_SUCCESS';
export const ADD_USER_TO_GROUP_ERROR = 'ADD_USER_TO_GROUP_ERROR';

export const REMOVE_USER_FROM_GROUP_PENDING = 'REMOVE_USER_FROM_GROUP_PENDING';
export const REMOVE_USER_FROM_GROUP_SUCCESS = 'REMOVE_USER_FROM_GROUP_SUCCESS';
export const REMOVE_USER_FROM_GROUP_ERROR = 'REMOVE_USER_FROM_GROUP_ERROR';