export const ADD_TEST_PENDING  = 'ADD_TEST_PENDING';
export const ADD_TEST_SUCCESS  = 'ADD_TEST_SUCCESS';
export const ADD_TEST_ERROR    = 'ADD_TEST_ERROR';

export const SAVE_TEST_PENDING  = 'SAVE_TEST_PENDING';
export const SAVE_TEST_SUCCESS  = 'SAVE_TEST_SUCCESS';
export const SAVE_TEST_ERROR    = 'SAVE_TEST_ERROR';

export const GET_TESTS_PENDING = 'GET_TESTS_PENDING';
export const GET_TESTS_SUCCESS = 'GET_TESTS_SUCCESS';
export const GET_TESTS_ERROR   = 'GET_TESTS_ERROR';

export const GET_TEST_PENDING = 'GET_TEST_PENDING';
export const GET_TEST_SUCCESS = 'GET_TEST_SUCCESS';
export const GET_TEST_ERROR = 'GET_TEST_ERROR';

export const GET_EVENTS_PENDING = 'GET_EVENTS_PENDING';
export const GET_EVENTS_SUCCESS = 'GET_EVENTS_SUCCESS';
export const GET_EVENTS_ERROR = 'GET_EVENTS_ERROR';