export const ADD_USER_PENDING  = 'ADD_USER_PENDING';
export const ADD_USER_SUCCESS  = 'ADD_USER_SUCCESS';
export const ADD_USER_ERROR    = 'ADD_USER_ERROR';

export const SAVE_USER_PENDING  = 'SAVE_USER_PENDING';
export const SAVE_USER_SUCCESS  = 'SAVE_USER_SUCCESS';
export const SAVE_USER_ERROR    = 'SAVE_USER_ERROR';

export const DELETE_USER_PENDING = 'DELETE_USER_PENDING';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_ERROR = 'DELETE_USER_ERROR';

export const GET_USER_PENDING  = 'GET_USER_PENDING';
export const GET_USER_SUCCESS  = 'GET_USER_SUCCESS';
export const GET_USER_ERROR    = 'GET_USER_ERROR';

export const GET_USERS_PENDING = 'GET_USERS_PENDING';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_ERROR   = 'GET_USERS_ERROR';
